CREATE TABLE `USERS` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `NAME` char(50) NOT NULL,
  `ROLE` char(30) NOT NULL,
  `USERNAME` char(50) NOT NULL,
  `PASSWORD` char(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;